### Products Index
GET http://localhost:3000/all_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc3MzU2MzV9.ck33JcxhA98EUy1vELuRm3i_KNPqdhKFGkITEcB4TZI

### Products Show

GET http://localhost:3000/products/3.json

### Products Create

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Draymond Green Jersey",
  "price": 80,
  "image_url": "https://woos.s3.amazonaws.com/wp-content/uploads/2022/06/08155332/1654411332d37720f164.jpeg",
  "description": "Black Draymond Green Jersey # 23"
}

### 2nd Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Black Gold Blooded Tshirt",
  "price": 35,
  "image_url": "https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productimages/_4910000/altimages/ff_4910471-2ae247022620a719b81aalt1_full.jpg&w=900",
  "description": "Black Gold Blooded 2022 Championship Tshirt"
}

### Products Update

PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
  "name" : "Clay Thompson Jersey"
}

### Products Destroy 
DELETE http://localhost:3000/products/6.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Walter White",
  "email": "heisenberg@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### 2nd Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Gustavo Fring",
  "email": "loshermanos@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "heisenberg@example.com",
  "password": "password"
}

### Sessions create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "heisenberg@example.com",
  "password": "password"
}

### Order Create
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTk1NTIxNTd9.SqDBwxvtf9XGArcVQl0R0mMHxutu09f_hD0EVESAs-c
Content-Type: application/json  

{
  "user_id": 12,
  "product_id": 2,
  "quantity": 10,
  "subtotal": 30,
  "tax": 3,
  "total": 33
}

### Carted Product Create
POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyNTU3MTZ9.pT7aU0J1_1sp44bzSZ1alWnLBLwOvHbW5mYsCL_Do6I
Content-Type: application/json

{
  "id": 1,
  "user_id": 1,
  "product_id": 8,
  "quantity": 10,
  "status": 30,
  "order_id": 3
}
